export const OVERDUE_FIRST_ALERT_DEFAULT_MINS = 60;
export const REMINDER_BATCH_SIZE = 100;
export const REMINDER_MAX_BATCHES_PER_RUN = 50;
export const REMINDER_RETRY_DELAY_MS = 5 * 60 * 1000;
export const RECONCILE_BATCH_SIZE = 500;
